package com.nowni.calculator.ui.theme

import androidx.compose.ui.graphics.Color

/*val Purple80 = Color(0xFFD0BCFF)
val PurpleGrey80 = Color(0xFFCCC2DC)
val Pink80 = Color(0xFFEFB8C8)

val Purple40 = Color(0xFF6650a4)
val PurpleGrey40 = Color(0xFF625b71)
val Pink40 = Color(0xFF7D5260)*/

// Light Theme
val primaryLight = Color(0xFFB0B0B0)
val onPrimaryLight = Color(0xFF000000)
val primaryContainerLight = Color(0xFFE0E0E0)
val onPrimaryContainerLight = Color(0xFF2E2E2E)
val secondaryLight = Color(0xFFCCCCCC)
val onSecondaryLight = Color(0xFF1A1A1A)
val secondaryContainerLight = Color(0xFFF0F0F0)
val onSecondaryContainerLight = Color(0xFF2E2E2E)
val tertiaryLight = Color(0xFFD6D6D6)
val onTertiaryLight = Color(0xFF1A1A1A)
val tertiaryContainerLight = Color(0xFFECECEC)
val onTertiaryContainerLight = Color(0xFF2E2E2E)
val errorLight = Color(0xFFD32F2F)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFE0E0)
val onErrorContainerLight = Color(0xFF7F0000)
val backgroundLight = Color(0xFFE0E0E0)
val onBackgroundLight = Color(0xFF2E2E2E)
val surfaceLight = Color(0xFFE0E0E0)
val onSurfaceLight = Color(0xFF2E2E2E)
val surfaceVariantLight = Color(0xFFD0D0D0)
val onSurfaceVariantLight = Color(0xFF3A3A3A)
val outlineLight = Color(0xFFA0A0A0)
val outlineVariantLight = Color(0xFFBDBDBD)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF3A3A3A)
val inverseOnSurfaceLight = Color(0xFFF5F5F5)
val inversePrimaryLight = Color(0xFF2E2E2E)
val surfaceDimLight = Color(0xFFD6D6D6)
val surfaceBrightLight = Color(0xFFEAEAEA)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF5F5F5)
val surfaceContainerLight = Color(0xFFECECEC)
val surfaceContainerHighLight = Color(0xFFE5E5E5)
val surfaceContainerHighestLight = Color(0xFFDCDCDC)

// Dark Theme
val primaryDark = Color(0xFF4A4A4A)
val onPrimaryDark = Color(0xFFE0E0E0)
val primaryContainerDark = Color(0xFF2E2E2E)
val onPrimaryContainerDark = Color(0xFFDCDCDC)
val secondaryDark = Color(0xFF3C3C3C)
val onSecondaryDark = Color(0xFFE0E0E0)
val secondaryContainerDark = Color(0xFF202020)
val onSecondaryContainerDark = Color(0xFFCCCCCC)
val tertiaryDark = Color(0xFF474747)
val onTertiaryDark = Color(0xFFE0E0E0)
val tertiaryContainerDark = Color(0xFF2A2A2A)
val onTertiaryContainerDark = Color(0xFFDADADA)
val errorDark = Color(0xFFFF6F6F)
val onErrorDark = Color(0xFF4A0000)
val errorContainerDark = Color(0xFF7F0000)
val onErrorContainerDark = Color(0xFFFFDADA)
val backgroundDark = Color(0xFF2E2E2E)
val onBackgroundDark = Color(0xFFE0E0E0)
val surfaceDark = Color(0xFF2E2E2E)
val onSurfaceDark = Color(0xFFE0E0E0)
val surfaceVariantDark = Color(0xFF3C3C3C)
val onSurfaceVariantDark = Color(0xFFCCCCCC)
val outlineDark = Color(0xFF555555)
val outlineVariantDark = Color(0xFF3A3A3A)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFDCDCDC)
val inverseOnSurfaceDark = Color(0xFF2E2E2E)
val inversePrimaryDark = Color(0xFFE0E0E0)
val surfaceDimDark = Color(0xFF1E1E1E)
val surfaceBrightDark = Color(0xFF353535)
val surfaceContainerLowestDark = Color(0xFF121212)
val surfaceContainerLowDark = Color(0xFF1C1C1C)
val surfaceContainerDark = Color(0xFF252525)
val surfaceContainerHighDark = Color(0xFF2F2F2F)
val surfaceContainerHighestDark = Color(0xFF383838)

